[package]
name = "stylus_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stylus-sdk = "0.4.2"
electron-rs = { path = "../electron-rs" }